import { Router } from 'express'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { query } from '../config/db.js'
import { authenticateToken, requireAdmin, requireCandidate, requireEmployee } from '../middleware/auth.js'

const router = Router()
const clean = value => typeof value === 'string' ? value.trim() : value
const tokenFor = user => jwt.sign({ id: user.id, role: user.role }, process.env.JWT_SECRET, { expiresIn: '7d' })
const setToken = (res, token) => res.cookie('kyk_token', token, {
  httpOnly: true,
  sameSite: process.env.NODE_ENV === 'production' ? 'none' : 'lax',
  secure: process.env.NODE_ENV === 'production',
  maxAge: 7 * 24 * 60 * 60 * 1000
})
router.post('/auth/register', async (req, res, next) => { try { const { name, email, password, phone } = req.body; if (!name || !email || !password || password.length < 8) return res.status(400).json({ message: 'Name, valid email, and an 8-character password are required.' }); const hash = await bcrypt.hash(password, 12); const result = await query('INSERT INTO users (name,email,password_hash,phone,role) VALUES (?,?,?,?,\'candidate\')', [clean(name), clean(email).toLowerCase(), hash, clean(phone) || null]); const user = { id: result.insertId, name: clean(name), email: clean(email).toLowerCase(), role: 'candidate' }; setToken(res, tokenFor(user)); res.status(201).json({ user }) } catch (e) { if (e.code === 'ER_DUP_ENTRY') return res.status(400).json({ message: 'An account with that email already exists.' }); next(e) } })
router.post('/auth/login', async (req, res, next) => { try { const { email, password } = req.body; const rows = await query('SELECT * FROM users WHERE email = ? LIMIT 1', [clean(email)?.toLowerCase()]); if (!rows[0] || !rows[0].is_active || !(await bcrypt.compare(password || '', rows[0].password_hash))) return res.status(401).json({ message: 'Email or password is incorrect.' }); const { password_hash, ...user } = rows[0]; setToken(res, tokenFor(user)); res.json({ user }) } catch (e) { next(e) } })
router.post('/auth/logout', (req, res) => { res.clearCookie('kyk_token'); res.json({ message: 'Logged out.' }) })
router.get('/auth/me', authenticateToken, (req, res) => res.json({ user: req.user }))

router.get('/jobs', async (req, res, next) => { try { const rows = await query('SELECT * FROM jobs WHERE status = \'open\' ORDER BY created_at DESC'); res.json({ jobs: rows }) } catch (e) { next(e) } })
router.get('/jobs/all', authenticateToken, requireAdmin, async (req, res, next) => { try { res.json({ jobs: await query('SELECT * FROM jobs ORDER BY created_at DESC') }) } catch (e) { next(e) } })
router.get('/jobs/:id', async (req, res, next) => { try { const rows = await query('SELECT * FROM jobs WHERE id = ? AND status = \'open\'', [req.params.id]); if (!rows[0]) return res.status(404).json({ message: 'Job not found.' }); res.json({ job: rows[0] }) } catch (e) { next(e) } })
router.post('/jobs', authenticateToken, requireAdmin, async (req, res, next) => { try { const { title, department, location, employment_type, experience, description, requirements, responsibilities, skills, salary, status = 'draft' } = req.body; if (!title) return res.status(400).json({ message: 'Job title is required.' }); const result = await query('INSERT INTO jobs (title,department,location,employment_type,experience,description,requirements,responsibilities,skills,salary,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)', [title,department,location,employment_type,experience,description,requirements,responsibilities,skills,salary,status]); res.status(201).json({ id: result.insertId }) } catch (e) { next(e) } })
router.put('/jobs/:id', authenticateToken, requireAdmin, async (req, res, next) => { try { const fields = ['title','department','location','employment_type','experience','description','requirements','responsibilities','skills','salary','status']; const values = fields.map(key => req.body[key]); await query(`UPDATE jobs SET ${fields.map(key => `${key} = ?`).join(', ')} WHERE id = ?`, [...values, req.params.id]); res.json({ message: 'Job updated.' }) } catch (e) { next(e) } })
router.delete('/jobs/:id', authenticateToken, requireAdmin, async (req, res, next) => { try { await query('DELETE FROM jobs WHERE id = ?', [req.params.id]); res.status(204).end() } catch (e) { next(e) } })

router.post('/applications', authenticateToken, requireCandidate, async (req, res, next) => { try { const { job_id, name, email, phone, resume_url, cover_letter } = req.body; if (!job_id || !name || !email) return res.status(400).json({ message: 'Job, name, and email are required.' }); const jobs = await query('SELECT id FROM jobs WHERE id = ? AND status = \'open\'', [job_id]); if (!jobs[0]) return res.status(400).json({ message: 'That job is no longer accepting applications.' }); const result = await query('INSERT INTO applications (job_id,candidate_id,name,email,phone,resume_url,cover_letter) VALUES (?,?,?,?,?,?,?)', [job_id, req.user.id, clean(name), clean(email).toLowerCase(), clean(phone) || null, clean(resume_url) || null, clean(cover_letter) || null]); res.status(201).json({ id: result.insertId, message: 'Application submitted successfully.' }) } catch (e) { next(e) } })
router.get('/applications', authenticateToken, requireAdmin, async (req, res, next) => { try { const rows = await query('SELECT a.*, j.title AS job_title FROM applications a JOIN jobs j ON j.id = a.job_id ORDER BY a.created_at DESC'); res.json({ applications: rows }) } catch (e) { next(e) } })
router.get('/applications/mine', authenticateToken, requireCandidate, async (req, res, next) => { try { const rows = await query('SELECT a.*, j.title AS job_title FROM applications a JOIN jobs j ON j.id = a.job_id WHERE a.candidate_id = ? OR (a.candidate_id IS NULL AND a.email = ?) ORDER BY a.created_at DESC', [req.user.id, req.user.email]); res.json({ applications: rows }) } catch (e) { next(e) } })
router.get('/applications/:id', authenticateToken, requireAdmin, async (req, res, next) => { try { const rows = await query('SELECT a.id, a.job_id, a.candidate_id, a.name, a.email, a.phone, a.resume_url, a.cover_letter, a.status, a.created_at, a.updated_at, j.title AS job_title FROM applications a JOIN jobs j ON j.id = a.job_id WHERE a.id = ? LIMIT 1', [req.params.id]); if (!rows[0]) return res.status(404).json({ message: 'Application not found.' }); res.json({ application: rows[0] }) } catch (e) { next(e) } })
router.put('/applications/:id', authenticateToken, requireAdmin, async (req, res, next) => { try { const allowed = ['submitted','reviewing','shortlisted','rejected','selected']; if (!allowed.includes(req.body.status)) return res.status(400).json({ message: 'Invalid application status.' }); await query('UPDATE applications SET status = ? WHERE id = ?', [req.body.status, req.params.id]); res.json({ message: 'Application status updated.' }) } catch (e) { next(e) } })

router.post('/contact', async (req, res, next) => { try { const { name, email, company, phone, inquiry_type, message } = req.body; if (!name || !email || !message) return res.status(400).json({ message: 'Name, email, and message are required.' }); await query('INSERT INTO contact_inquiries (name,email,company,phone,inquiry_type,message) VALUES (?,?,?,?,?,?)', [clean(name), clean(email).toLowerCase(), clean(company) || null, clean(phone) || null, clean(inquiry_type) || null, clean(message)]); res.status(201).json({ message: 'Thanks — your inquiry has been received.' }) } catch (e) { next(e) } })
router.get('/contact', authenticateToken, requireAdmin, async (req, res, next) => { try { res.json({ inquiries: await query('SELECT * FROM contact_inquiries ORDER BY created_at DESC') }) } catch (e) { next(e) } })
router.put('/contact/:id', authenticateToken, requireAdmin, async (req, res, next) => { try { if (!['new','read','resolved'].includes(req.body.status)) return res.status(400).json({ message: 'Invalid inquiry status.' }); await query('UPDATE contact_inquiries SET status = ? WHERE id = ?', [req.body.status, req.params.id]); res.json({ message: 'Inquiry updated.' }) } catch (e) { next(e) } })

router.get('/employees', authenticateToken, requireAdmin, async (req, res, next) => { try { res.json({ employees: await query('SELECT id,name,email,phone,is_active,created_at FROM users WHERE role = \'employee\' ORDER BY name') }) } catch (e) { next(e) } })
router.get('/employee/me', authenticateToken, requireEmployee, (req, res) => res.json({ employee: req.user }))
router.get('/dashboard', authenticateToken, requireAdmin, async (req, res, next) => { try { const [[employees], [jobs], [applications], [contacts]] = await Promise.all([query('SELECT COUNT(*) AS total FROM users WHERE role = \'employee\' AND is_active = 1'), query('SELECT COUNT(*) AS total FROM jobs WHERE status = \'open\''), query('SELECT COUNT(*) AS total FROM applications'), query('SELECT COUNT(*) AS total FROM contact_inquiries WHERE status != \'resolved\'')]); res.json({ employees: employees.total, jobs: jobs.total, applications: applications.total, contacts: contacts.total }) } catch (e) { next(e) } })

export default router
